name: AndroidBuild

env:
  main_project_module: app

  playstore_name: Tic Tac Toe Advance

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
  android_tests:
    runs-on:
      - ubuntu-latest
      # [ macos-12 ]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew
      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest
  build_debug:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/